services:
  binfmt_misc:
    image: tonistiigi/binfmt
    command: --install all
    privileged: true
    restart: always

  mt5:
    depends_on:
      - binfmt_misc
    build: .
    container_name: mt5
    volumes:
      - ./metatrader:/config
    environment:
      - MT_BACKGROUND=true
    ports:
      - 3000:3000
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "2G"
