services:
  binfmt_misc:
    image: tonistiigi/binfmt
    command: --install all
    privileged: true
    restart: "no"

  mt5:
    depends_on:
      - binfmt_misc
    build: .
    container_name: mt5
    volumes:
      - ./metatrader:/config
    environment:
      - MT_BACKGROUND=false
    ports:
      - 3000:3000
